name: ENV variables
on: push

env: 
  Env_variable : Global-variable
  secret: ${{ secrets.secret1 }}
      
jobs:
  jobA: 
    runs-on: ubuntu-latest
    env:
      Env_variable: Job-Variable
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt file example
      #  env:
         # Env_variable : Step-Variable
        run: |
          base64 sample.json >> encrypted.json
          echo $enrypted.json
