name: ENV variables
on: push
env: 
  Env_variable : Global-variable
  secret: ${{ secrets.secret1 }}
jobs:
  jobA: 
    runs-on: ubuntu-latest
    env:
      Env_variable: Job-Variable
    steps:
      - name: Display ENV variables
      #  env:
         # Env_variable : Step-Variable
        run: echo $secret
 
